# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - SMSAppDocker

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_800368bfafe74f32bf8e930e58477178 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_277d2dfec72c4e43b1e0bc0585af44d6 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.AzureAppService_ContainerUsername_800368bfafe74f32bf8e930e58477178 }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'SMSAppDocker'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_026cbd7310bb4eb6b028d9e2f2a0fb84 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_800368bfafe74f32bf8e930e58477178 }}/appsvc/staticsite:${{ github.sha }}'